config/routes.rb
Rails.application.routes.draw do
 get 'top/main'
 post 'top/login'
 root 'top#main'
 get 'top/logout'
 resources :users, only: [:index, :new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ActiveRecord::Base
 validates :uid, uniqueness: true
 def self.authenticate(uid, pass)
  if user = find_by(uid: uid, pass: pass)
   user
  else
   nil
  end
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 def L4
 session[:c] ||=0
 session[:c] = session[:c].to_i + 1
 render plain: session[:c]
 end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
   def main
    if session[:login_uid]
      render 'main'
    else
      render 'login'
    end
   end
   def login
   if User.authenticate(params[:uid],params[:pass])
   session[:login] = params[:uid]
   redirect_to top_main_path
   else
   render"error"
   end
   def logout
    session.delete(:login_uid)
    redirect_to top_main_path
   end
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
   def new
     @users = user = User.new
   end
    def create
        user = User.new(uid: params[:uid],pass: params[:pass])
        user.save
        redirect_to '/'
    end
     def destroy
         user = User.find(params[:uid],params[:pass])
         user.destroy
         redirect_to '/'
     end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L4</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/error.html.erb
<form_tag '/top/error', method: :post do %>
 <p>
 <strong>ログイン失敗！</strong>
 </p>
 <%= link_to '戻る', :back %>

app/views/top/index.html.erb
<h1>Top#index</h1>
<p>Find me in app/views/top/index.html.erb</p>

app/views/top/login.html.erb
<%= form_tag '/top/login', method: :post do %>
 <p><%= label_tag :uid, 'ユーザーID' %>
 <%= text_field_tag :uid %></p>
 <p><%= label_tag :pass, 'パスワード' %>
 <%= password_field_tag :pass %></p>
 <p><%= submit_tag 'ログイン' %></p>
<% end %>
<%= button_to 'ユーザー登録', new_user_path, method: :get %>

app/views/top/main.html.erb
<form_tag '/top/main', method: :post do %>
 <p>
 <strong>ログイン中です</strong>
 </p>
 <%= button_to 'ログアウト', top_logout_path(session[:login_uid]), method: :get %>

app/views/users/index.html.erb
<% @users.each do |user| %>
<p> <%= link_to user.uid, user.pass %>
 <%= link_to '削除', "users/#{user.id}", method: :delete %>
 <%= link_to '表示', "users/#{user.id}" %>
 <%= link_to '編集', "users/#{user.id}/edit" %>
</p>
<% end %>
<p><%= link_to '新規追加', 'users/new' %></p>

app/views/users/new.html.erb
<%= form_for @users , url: {action: :create} do |f| %>
 <p><%= f.label :uid, 'ユーザーID' %>
 <%= f.text_field :uid %></p>
 <p><%= f.label :pass, 'パスワード' %>
 <%= f.password_field :pass %></p>
 <p><%= f.submit '登録' %></p>
<% end %>